### PR TITLE
Add UnitTest using spectre-build

### PR DESCRIPTION
**Pull request by toshi0383**
Not working in my workspace (swift-2.2-SNAPSHOT-2016-01-11-a)

```
Queue $ .build/debug/spectre-build
Tests/QueueSpec.swift:2:8: error: no such module 'Queue'
import Queue
       ^
InvocationError()
```

### CODE REVIEW

**Comment by toshi0383** [comment]
Working in travis-ci, so merging this anyways.
